environment:
  TEST_FILES_UTF8: internal api user encodings01 encodings02 encodings03 encodings04 encodings05 encodings06 encodings07 encodings08 compilation-utf8
  TEST_FILES_GBK_BIG5: cjk01 cjk02 cjk03 encodings01 encodings02 encodings03 encodings04 encodings05 encodings06 encodings07 encodings08 compilation-gbk compilation-big5

install:
  - ps: .appveyor\texlive\install.ps1

build: off

test_script:
  - ps: ./artratex.bat

cache:
  - C:\texlive
