environment:
  TEST_FILES_UTF8: internal api user encodings01 encodings02 encodings03 encodings04 encodings05 encodings06 encodings07 encodings08 compilation-utf8
  TEST_FILES_GBK_BIG5: cjk01 cjk02 cjk03 encodings01 encodings02 encodings03 encodings04 encodings05 encodings06 encodings07 encodings08 compilation-gbk compilation-big5

install:
  - ps: .appveyor\texlive\install.ps1
  - Invoke-WebRequest -Uri https://intellisenselab.ml/%E4%B9%89%E5%90%AF%E7%B2%97%E6%A5%B7%E4%BD%93.ttf `
                      -OutFile "iekie cukai.ttf"
  -  mv '.\iekie cukai.ttf' C:\Windows\Fonts\

build: off

test_script:
  - ps: ./artratex.bat

cache:
  - C:\texlive
