branches:
  only:
  - dev
  
jobs:
  include:
    - name: TeX Live (Linux)
      os: linux
      dist: bionic
      sudo: required
      addons:
        apt:
          packages:
            # Chinese
            - language-pack-zh*
            - chinese*
      before_install:
        - sudo apt-get update
      install:
        - sudo apt-get -y install texlive-full
      script:
        - chmod +x artratex.sh
        - ./artratex.sh xa
      cache:
        directories:
          - /tmp/texlive
          - $HOME/.texlive
    - name: TeX Live (macOS)
      os: osx
      sudo: required
      addons:
        apt:
          packages:
            # Chinese
            - language-pack-zh*
            - chinese*
      before_install:
        - sudo apt-get update
      install:
        - sudo apt-get -y install texlive-full
      script:
        - chmod +x artratex.sh
        - ./artratex.sh xa
      cache:
        directories:
          - /tmp/texlive
          - $HOME/.texlive


