branches:
  only:
  - dev
  
jobs:
  include:
    - name: TeX Live (Linux)
      os: linux
      dist: bionic
      sudo: required
      addons:
        apt:
          packages:
            # Chinese
            - language-pack-zh*
            - chinese*
      before_install:
        - sudo apt-get update
        - sudo apt install perl wget -y
      install:
        - wget http://mirrors.ctan.org/systems/texlive/Images/texlive2019-20190410.iso
        - wget http://mirrors.ctan.org/systems/texlive/Images/texlive2019-20190410.iso.md5
        - md5sum -c texlive2019-20190410.iso.md5
        - sudo mkdir /home/download
        - sudo mount -o loop,ro *.iso /home/download
        - echo 'I' | sudo tee /home/test.txt 
        - cat /home/test.txt | nohup perl /home/download/install-tl -no-gui
        - sudo umount -l /home/download/
        - sudo cp /usr/local/texlive/2019/texmf-var/fonts/conf/texlive-fontconfig.conf /etc/fonts/conf.d/09-texlive.conf
        - sudo nohup fc-cache -fsv
      script:
        - export PATH=/usr/local/texlive/2019/bin/x86_64-linux:$PATH
        - sudo sed -i '86,103d' artratex.sh
        - sudo chmod +x artratex.sh
        - ./artratex.sh xa
      cache:
        directories:
          - /tmp/texlive
          - $HOME/.texlive
    - name: TeX Live (macOS)
      os: osx
      sudo: required
      addons:
        brew:
          packages:
            # Chinese
            - language-pack-zh*
            - chinese*
      before_install:
        - brew  update
        - brew install wget perl
      install:
        - wget http://mirrors.ctan.org/systems/texlive/Images/texlive2019-20190410.iso
        - wget http://mirrors.ctan.org/systems/texlive/Images/texlive2019-20190410.iso.md5
        - md5sum -c texlive2019-20190410.iso.md5
        - sudo mkdir /home/download
        - hdiutil attach -mountroot /home/download
        - echo 'I' | sudo tee /home/test.txt 
        - cat /home/test.txt | nohup perl /home/download/install-tl -no-gui
        - sudo cp /usr/local/texlive/2019/texmf-var/fonts/conf/texlive-fontconfig.conf /etc/fonts/conf.d/09-texlive.conf
        - sudo nohup fc-cache -fsv
      script:
        - export PATH=/usr/local/texlive/2019/bin/x86_64-linux:$PATH
        - sudo sed -i '86,103d' artratex.sh
        - sudo chmod +x artratex.sh
        - ./artratex.sh xa
      cache:
        directories:
          - /tmp/texlive
          - $HOME/.texlive

